language: ruby
cache: bundler
rvm:
  - 2.6
  - 2.4

before_install: gem update --system
install: script/bootstrap
script: script/cibuild

env:
  matrix:
    - JEKYLL_VERSION="~> 3.5"
    - JEKYLL_VERSION="~> 3.8.0"
    - JEKYLL_VERSION=">= 4.0.0.pre.alpha1"
